version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
      - "22:22"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
