version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    depends_on:
      - base-image

  base-image:
    build: 
      context: .
      dockerfile: Dockerfile-gatsby
    image: gatsby:v1